### ISSUE TITLE
advanced-renamer outdated and packages broken

### ISSUE THREAD

**Issue by welwood08** [Link-Satonaka/chocopkgs#9]
Hi, Advanced Renamer 3.77 was released on the same day that the `.install` package for 3.76 was approved. Attempting to update an older installation via chocolatey fails because the version downloaded (3.77) does not match the checksum expected (3.76).

Obviously the quick fix is to simply release a new package, but I think there's an opportunity to improve the package to avoid this problem in the future.

According to [the chocolatey contribution guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed) it is now recommended to embed the installer in the package where possible. If I understand correctly, Advanced Renamer's [license](https://www.advancedrenamer.com/user_guide/license) specifically permits this use case. Doing this will mean that the package is decoupled and won't break if upstream releases a new version.

Embedding the installer in the package will also enable the package to [support multiple versions](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#115-support-multiple-versions), useful for example in case the latest version causes problems then an older version can be installed manually.

If some examples of other packages using this method would be helpful, please see chocolatey/chocolatey-coreteampackages@c76520311ea51b4e4b2a24ca3e7c6d9b55e4db2a and niks255/ChocolateyPackages@2f27851f71f88817f1005958c865828397890dc9.

**Comment by Link-Satonaka** [comment]
Honestly, it would be a lot nicer if chocolatey implemented some host verification check instead of relying on checksum for installers that are updated in-place, like this one.

Then packages wouldn't break all of the time, and users could grab the latest version whenever they wanted without needing the maintainer to update it, by simply reinstalling the package.

I'll implement your suggestion soon, but for now I'll be fixing/updating the package, thanks for bringing it to my attention.

**Comment by Link-Satonaka** [comment]
Fixed this a while back
